### ISSUE TITLE
To-Do List before due date

### ISSUE THREAD

**Issue by ammmyd** [GeniusXanthron/1K6-Group-4-AS1-CS#1]
**Due date**: 1 June 2022, 12:00 AM

To-Do:

- [x] Make search results page
~~*(put a table on the index page as placeholder)*~~
- [x] Replace the colors for the ones that are school-themed
- [x] Make all pages compatible with mobile devices

**Comment by Coral-Reefs** [comment]
Oops-
How do they even open it on mobile?

**Comment by ammmyd** [comment]
They have an app...

**Comment by ammmyd** [comment]
That "commit" thing wasn't intentional.

**Comment by ammmyd** [comment]
DONE!

**Comment by Coral-Reefs** [comment]
Wait what but hey need xampp and-

**Comment by ammmyd** [comment]
Can just put some more to-dos and reopen this e
